{% set version = "1.9.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-waterml
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/WaterML_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/WaterML/WaterML_{{ version }}.tar.gz
  sha256: 499f7c6bb0fe3e560c4754723ec0686a1bda3973689820eea0917bd77f6c84b2

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-xml
    - r-httr
  run:
    - r-base
    - r-xml
    - r-httr

test:
  commands:
    - $R -e "library('WaterML')"           # [not win]
    - "\"%R%\" -e \"library('WaterML')\""  # [win]

about:
  home: https://github.com/jirikadlec2/waterml
  license: MIT
  summary: "Lets you connect to any of the 'Consortium of Universities for the Advancement of Hydrological Science, Inc.' ('CUAHSI') Water Data Center 'WaterOneFlow' web services and read any 'WaterML' time series data file. To see list of available web services, see <http://hiscentral.cuahsi.org>. All versions of 'WaterML'\
    \ (1.0, 1.1 and 2.0) and both types of the web service protocol ('SOAP' and 'REST') are supported. The package has six data download functions: GetServices(): show all public web services from the HIS Central Catalog. HISCentral_GetSites() and HISCentral_GetSeriesCatalog(): search for sites or time series from the HIS\
    \ Central catalog based on geographic bounding box, server, or keyword. GetVariables(): Show a data.frame with all variables on the server. GetSites(): Show a data.frame with all sites on the server. GetSiteInfo(): Show what variables, methods and quality control levels are available at the specific site. GetValues():\
    \ Given a site code, variable code, start time and end time, fetch a data.frame of all the observation time series data values. The GetValues() function can also parse 'WaterML' data from a custom URL or from a local file."
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: WaterML
# Type: Package
# Title: Fetch and Analyze Data from 'WaterML' and 'WaterOneFlow' Web Services
# Version: 1.9.0
# Authors@R: person("Jiri","Kadlec", email="jirikadlec2@gmail.com", role=c("aut", "cre"))
# Description: Lets you connect to any of the 'Consortium of Universities for the Advancement of Hydrological Science, Inc.' ('CUAHSI') Water Data Center 'WaterOneFlow' web services and read any 'WaterML' time series data file. To see list of available web services, see <http://hiscentral.cuahsi.org>. All versions of 'WaterML' (1.0, 1.1 and 2.0) and both types of the web service protocol ('SOAP' and 'REST') are supported. The package has six data download functions: GetServices(): show all public web services from the HIS Central Catalog. HISCentral_GetSites() and HISCentral_GetSeriesCatalog(): search for sites or time series from the HIS Central catalog based on geographic bounding box, server, or keyword. GetVariables(): Show a data.frame with all variables on the server. GetSites(): Show a data.frame with all sites on the server. GetSiteInfo(): Show what variables, methods and quality control levels are available at the specific site. GetValues(): Given a site code, variable code, start time and end time, fetch a data.frame of all the observation time series data values. The GetValues() function can also parse 'WaterML' data from a custom URL or from a local file.
# License: MIT + file LICENSE
# Depends: R (>= 3.0)
# Imports: stats, XML, httr
# LazyData: true
# URL: https://github.com/jirikadlec2/waterml
# Suggests: knitr, qpdf
# VignetteBuilder: knitr
# RoxygenNote: 7.0.2
# NeedsCompilation: no
# Packaged: 2020-02-12 01:00:03 UTC; Admin
# Author: Jiri Kadlec [aut, cre]
# Maintainer: Jiri Kadlec <jirikadlec2@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-02-12 10:50:05 UTC
