travis:
  secure:
    BINSTAR_TOKEN: DKhPaY/j7BauWSke/DRojrLz+bwqWo6s2IzRDAUK7xpUjJ6eRLi12CK8WoFld40jhYe+lPNSGMjdxefr/Ttel6bPaidpsIQX4MdVCbm3fKkVHKbPGnS22yYFre5QTiFIYbKdjtqlxcwNGbl9O9b4Agfp/loXGfFCZ2r9wASLNj3YGfg/qxhrIkVRRWI3H0TP4dDpRk+CmrBsvD7J4VZYQrJLstVKzGTEyBAe9XAPuTPCzedIQbe1yAOuWY5oapfRWbCMTwv/NtGxWTj3H9qA05hKpwgeQSR6CBgfbdg0ivMIOt8XRAzqXSfvCuM4IpxQ+1yjEYPXHCJbNQ9wZt/lmClY9dk4PgfJJBdlHmwsELFXYkSv34vf5lXQhFG8QnunWe4mosORRBsKLquqTujH+QESYu92odYGA+zx85QM+Fl8ip/DKpOLXNRIqLUkC5VYse3Ow5Dt8b9/fCH9FBBJw4kw6/K36xqqlmPenLaaoNJ/l7Aj2lOLkJoKCSPqgbPsGtcZ+Kijc/DKXEOW/70b4iYWnG27mD++cQ/RVcGPI3mfAjDZVc18iOUIPdlq5jY2jqMx6UAthgiggsg2YrkhGozvLw3wsEx2J0wo6VnhIJ5gjcItQ/RDrPc03v7dd4pk8bQoZwo4Y8VHdBGPNGHWDY8VFdgm+CPjwLyKsyllDHc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
