appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: MkWHNEGjfJLi9qk6go7yBGSgo4Emp8O6XOEGGeIXCCEXLxNDHk2FmvjfcjNPdXNfDWKzpZIxedvWRjF8uby7mjDeXaIYyKnMTZ5526rC4yatPPxi6zkrfP7h2zpqm2FMTNFUCuCfZQguBBDCMz0qLzGK7rffzteXIFRtbCwVLAD/LlyYxzGICEvSZJ+rWsvTb09blj7g7efEoAZK4WaYv3p+niXUClP7Y5MMccFfjaPiCkosvm3KkilPjbD8YHJgmZg3W7NJBKjdjOXAqDu7i+euTqvE+7iT9ft/RkmeOVQkf8el9HMAkET9ZArvefRQrZTsoKmCFqrhNoHttmvb9t8G+ycJ9nT4FSbQgTgrdxjOjZdyAJFwPowPm1IfMu3nU9Cci+OXo8zpnPecp26ffGRY3SQZoTQDTUkNpeJp+JMw+LzVgR/7YgEV0LKBLPOs3ivxtd9R6y7UzsdZbu/BLU6tQOn18ytmXy0VsG3f8yKVkmRPS0AWhSgCpO9axcDQaJ/6oZDmtEmdONtOc5kkshxnIOMuUwqv5v9zphzy5b5Cmr2JGBQYS/V753wtPgBcmIp75D83KdO4ydWJ2M8FO6h+7YAFj7oJkUuTPyr0J/d6l4PYoPeZRboYup2XdqdCtPMcL6L3VYy/b0AhLVNWgQxr4zj+JbS3QZj34DsVHHg=}
bot:
  automerge: true
